In [14]:
import duckdb
import pandas as pd

server="oss.resilientservice.mooo.com"
bucket= "resilentpublic"
bucket= "test"
s3_setup="""CREATE OR REPLACE SECRET s3_credentials(
    TYPE s3,

    ENDPOINT 'oss.resilientservice.mooo.com',
    URL_STYLE 'path'
);
"""
con = duckdb.connect()
con.execute(s3_setup)

# APCD H2S

In [4]:
hs2s_base="latest/tijuana/sd_apcd_air/h2s"
hs2name_pattern="*.parquet"
hs2_files=f"s3://{bucket}/{hs2s_base}/{hs2name_pattern}"

hs2_data2=con.read_parquet(hs2_files).df()
hs2_data2

,SiteName,Latitude,Longitude,AgencyName,LongName,Parameter,Site Name,Date with time,Result,Qualifier,Original Value,Icons,aggregation_year,date_processed,level
0,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T00:00:00-08:00,3.3,,3.3,place,2023,2025-11-25T02:37:57.931181,green
1,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T01:00:00-08:00,1.0,,1.0,place,2023,2025-11-25T02:37:57.931181,green
2,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T02:00:00-08:00,0.1,,.1,place,2023,2025-11-25T02:37:57.931181,green
3,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T03:00:00-08:00,0.0,,.0,place,2023,2025-11-25T02:37:57.931181,green
4,SAN YSIDRO,32.552794,-117.047286,San Diego APCD,San Ysidro,07 H2S PPB,SAN YSIDRO,2023-11-20T04:00:00-08:00,0.0,,.0,place,2023,2025-11-25T02:37:57.931181,green
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11811,IB CIVIC CTR,32.576139,-117.115361,San Diego APCD,Imperial Beach Civic Center,07 H2S PPB,IB CIVIC CTR,2024-12-30T19:00:00-08:00,17.8,,17.8,place,2024,2025-11-25T02:37:40.288369,yellow
11812,IB CIVIC CTR,32.576139,-117.115361,San Diego APCD,Imperial Beach Civic Center,07 H2S PPB,IB CIVIC CTR,2024-12-30T20:00:00-08:00,16.1,,16.1,place,2024,2025-11-25T02:37:40.288369,yellow
11813,IB CIVIC CTR,32.576139,-117.115361,San Diego APCD,Imperial Beach Civic Center,07 H2S PPB,IB CIVIC CTR,2024-12-30T21:00:00-08:00,9.3,,9.3,place,2024,2025-11-25T02:37:40.288369,yellow
11814,IB CIVIC CTR,32.576139,-117.115361,San Diego APCD,Imperial Beach Civic Center,07 H2S PPB,IB CIVIC CTR,2024-12-30T22:00:00-08:00,5.0,,5.0,place,2024,2025-11-25T02:37:40.288369,yellow
11815,IB CIVIC CTR,32.576139,-117.115361,San Diego APCD,Imperial Beach Civic Center,07 H2S PPB,IB CIVIC CTR,2024-12-30T23:00:00-08:00,1.6,,1.6,place,2024,2025-11-25T02:37:40.288369,green

# IBWC Streamflow at boundary
Data from 2020 and later

In [10]:
sf_base="latest/tijuana/streamflow/boundary_cms"
sf_name_pattern="*.parquet"
sf_files=f"s3://{bucket}/{sf_base}/{sf_name_pattern}"

sf_data=con.read_parquet(sf_files).df()
sf_data

,End of Interval (UTC-08:00),Average (m^3/s),Start of Interval (UTC-08:00)
0,2020-01-01 01:00:00,4.98,2020-01-01 00:00:00
1,2020-01-01 02:00:00,4.68,2020-01-01 01:00:00
2,2020-01-01 03:00:00,4.57,2020-01-01 02:00:00
3,2020-01-01 04:00:00,4.32,2020-01-01 03:00:00
4,2020-01-01 05:00:00,4.15,2020-01-01 04:00:00
...,...,...,...
43723,2024-12-30 20:00:00,1.50,2024-12-30 19:00:00
43724,2024-12-30 21:00:00,1.74,2024-12-30 20:00:00
43725,2024-12-30 22:00:00,1.50,2024-12-30 21:00:00
43726,2024-12-30 23:00:00,1.56,2024-12-30 22:00:00
43727,2024-12-31 00:00:00,1.57,2024-12-30 23:00:00

# openmeto weather
This demos how to use csv as input

In [15]:
om_base="tijuana/weather/raw"
om_name_pattern="*.csv"
om_files=f"s3://{bucket}/{om_base}/{om_name_pattern}"

om_data=con.read_csv(om_files).df()
om_data

,date,temperature_2m,wind_speed_10m,wind_direction_10m,wind_gusts_10m,precipitation,relative_humidity_2m,surface_pressure,cloud_cover,visibility,dewpoint_2m
0,2019-12-31 16:00:00-08:00,2.1085,10.308831,282.09473,19.440000,0.0,94.101510,1028.73910,3.0,None,1.2585
1,2019-12-31 17:00:00-08:00,1.8085,11.159999,270.00000,18.720000,0.0,95.450040,1028.43500,12.0,None,1.1585
2,2019-12-31 18:00:00-08:00,1.2085,10.137692,276.11542,18.720000,0.0,96.466430,1028.72300,3.0,None,0.7085
3,2019-12-31 19:00:00-08:00,0.3585,9.422101,276.58185,16.919998,0.0,97.497505,1028.70810,5.0,None,0.0085
4,2019-12-31 20:00:00-08:00,-0.0415,9.422101,276.58185,15.840000,0.0,97.135290,1028.80020,6.0,None,-0.4415
...,...,...,...,...,...,...,...,...,...,...,...
51619,2025-11-20 11:00:00-08:00,0.7585,15.763107,263.44315,32.399998,0.0,91.675970,1006.81915,32.0,None,-0.4415
51620,2025-11-20 12:00:00-08:00,0.3085,15.427586,262.62630,32.760002,0.0,89.986130,1007.80650,0.0,None,-1.1415
51621,2025-11-20 13:00:00-08:00,-0.1915,14.120538,258.97660,31.680000,0.0,89.946880,1008.49440,0.0,None,-1.6415
51622,2025-11-20 14:00:00-08:00,-0.6415,12.125642,264.03560,28.800000,0.0,90.243610,1009.08360,2.0,None,-2.0415
51623,2025-11-20 15:00:00-08:00,-1.0415,10.674773,275.80664,24.119999,0.0,91.556786,1009.67380,0.0,None,-2.2415